export const themeVars = {
  background: "var(--background)",
  foreground: "var(--foreground)",
  primary: "var(--primary)",
  primaryHover: "var(--primary-hover)",
  primaryActive: "var(--primary-active)",
  secondary: "var(--secondary)",
  secondaryHover: "var(--secondary-hover)",
  secondaryActive: "var(--secondary-active)",
  accent: "var(--accent)",
  accentHover: "var(--accent-hover)",
  accentActive: "var(--accent-active)",
  warning: "var(--warning)",
  warningHover: "var(--warning-hover)",
  warningActive: "var(--warning-active)",
  destructive: "var(--destructive)",
  destructiveHover: "var(--destructive-hover)",
  destructiveActive: "var(--destructive-active)",
  neoCyan: "var(--neo-cyan)",
  neoPink: "var(--neo-pink)",
  neoGreen: "var(--neo-green)",
  neoOrange: "var(--neo-orange)",
  neoYellow: "var(--neo-yellow)",
};
